### ISSUE TITLE
License problem

### ISSUE THREAD

**Issue by Tdue21** [jacobmesu/Guifreaks-Navisuite#1]
I have a slight problem with the license for the control. According to the [Read Me](../blob/master/README.md), the license is MIT, but the [License](../blob/master/LICENSE) is BSD-3-Clause as far as I can tell. 

So, what is it?

**Comment by jacobmesu** [comment]
Thnx, I changed the text in the license file to MIT, but I can license it under BSD-3-Clause if you prefer. Both are almost the same in terms of conditions. BSD-3 is even a more stricter license, but I presume you don't want to use my name to promote your own product, :)

**Comment by Tdue21** [comment]
Oh, I was just wondering which License that was actual in effect :)
Thanks for clarifying.
