### ISSUE TITLE
Is it possible to merge this project?

### ISSUE THREAD

**Issue by PWagner1** [jacobmesu/Guifreaks-Navisuite#3]
Hi @jacobmesu 

I'm the owner of [Krypton Toolkit Suite Extended .NET 5.470](https://github.com/Wagnerp/Krypton-Toolkit-Suite-Extended-NET-5.470), and was wondering if it was ok to merge this code into it? (Of course I'll give you credit)

**Comment by jacobmesu** [comment]
Hi Peter, 

Sure, go ahead.

**Comment by PWagner1** [comment]
Hi @jacobmesu 

Thanks for confirming. It should appear in the May update.
